version: '3.8'

services:
  web:
    build:
      context: .
      args:
        FLASK_APP: ${FLASK_APP}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    container_name: microblog
    ports:
      - "5000:5000"
    env_file: 
      - .env
    volumes:
      - ./app:/app
      - ./migrations:/migrations
      - app_data:/app_data
    depends_on:
      - db
    networks:
      - app_network
    command: ["./boot.sh"]

  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:
  app_data:

networks:
  app_network:
    driver: bridge
